# Generated by Django 5.2.6 on 2025-09-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('documento_url', models.URLField(blank=True, null=True)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('contrato_PDF', models.URLField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_propietario', to='administracion.persona')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
            },
        ),
    ]
