# Generated by Django 5.2 on 2025-09-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado_inquilino', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='Estado del Inquilino')),
                ('propietario', models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='inquilinos_propietario', to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'db_table': 'inquilino',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Motocicleta', 'Motocicleta'), ('Furgoneta', 'Furgoneta'), ('Crossover', 'Crossover')], max_length=20, verbose_name='Tipo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculo/', verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
