# Generated by Django 5.2.6 on 2025-09-21 04:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Bloque')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('numero_pisos', models.PositiveIntegerField(default=1, verbose_name='Número de Pisos')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'bloque',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.persona', verbose_name='Persona')),
                ('tipo_propietario', models.CharField(choices=[('P', 'Propietario'), ('C', 'Copropietario'), ('A', 'Arrendatario')], default='P', max_length=1, verbose_name='Tipo de Propietario')),
                ('fecha_registro_propietario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro como Propietario')),
                ('estado_propietario', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido'), ('P', 'Pendiente')], default='A', max_length=1, verbose_name='Estado del Propietario')),
                ('porcentaje_propiedad', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de Propiedad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Alternativo')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Alternativo')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietario',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, verbose_name='Número de Unidad')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Unidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensiones')),
                ('tipo_unidad', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('L', 'Local Comercial'), ('E', 'Estacionamiento')], default='A', max_length=1, verbose_name='Tipo de Unidad')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupada'), ('M', 'En Mantenimiento'), ('R', 'Reservada')], default='D', max_length=1, verbose_name='Estado')),
                ('numero_piso', models.PositiveIntegerField(default=1, verbose_name='Número de Piso')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área en m²')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residencial.bloque', verbose_name='Bloque')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['bloque__nombre', 'numero_piso', 'numero'],
                'unique_together': {('bloque', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuota Mensual')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Total')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('V', 'Vencido'), ('S', 'Suspendido'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Estado')),
                ('tipo_contrato', models.CharField(choices=[('P', 'Propiedad'), ('A', 'Arrendamiento'), ('C', 'Comodato')], default='P', max_length=1, verbose_name='Tipo de Contrato')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencial.propietario', verbose_name='Propietario')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencial.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
