# Generated by Django 5.2.6 on 2025-09-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='tipo_propietario',
        ),
    ]
