# Generated by Django 5.2 on 2025-09-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo'), ('HIJA', 'Hija'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('ESPOSO', 'Esposo'), ('ESPOSA', 'Esposa')], max_length=10, verbose_name='Parentesco')),
                ('persona_relacionada', models.ForeignKey(limit_choices_to={'tipo__in': ['P', 'I']}, on_delete=django.db.models.deletion.CASCADE, related_name='familiares_de', to='residencial.familiares', verbose_name='Persona Relacionada')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'db_table': 'familiares',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
    ]
