# Generated by Django 5.2.6 on 2025-09-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0002_remove_propietario_tipo_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='email_alternativo',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='porcentaje_propiedad',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='telefono_alternativo',
        ),
    ]
