# Generated by Django 5.2.6 on 2025-09-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
        ('residencial', '0002_familiares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='persona_relacionada',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['P', 'I']}, on_delete=django.db.models.deletion.CASCADE, related_name='familiares_de', to='administracion.persona', verbose_name='Persona Relacionada'),
        ),
    ]
