# Generated by Django 5.2.6 on 2025-09-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0003_remove_propietario_email_alternativo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
