# Generated by Django 5.2.6 on 2025-09-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
        ('residencial', '0003_alter_familiares_persona_relacionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('motivo_visita', models.CharField(choices=[('FAMILIA', 'Visita Familiar'), ('TRABAJO', 'Trabajo'), ('SERVICIO', 'Servicio'), ('SOCIAL', 'Social'), ('OTRO', 'Otro')], default='FAMILIA', max_length=10, verbose_name='Motivo de Visita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
    ]
