# Generated by Django 5.2.6 on 2025-09-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_empleado_supervisor'),
        ('residencial', '0004_delete_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Motocicleta', 'Motocicleta'), ('Furgoneta', 'Furgoneta'), ('Crossover', 'Crossover')], max_length=20, verbose_name='Tipo')),
                ('imagen', models.ImageField(upload_to='vehiculo/', verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.persona')),
            ],
        ),
    ]
