# Generated by Django 5.2 on 2025-09-27 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
        ('residencial', '0004_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], default='PERRO', max_length=10, verbose_name='Especie')),
                ('tipo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], default='MACHO', max_length=10, verbose_name='Tipo')),
                ('foto', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
