# Generated by Django 5.2.6 on 2025-09-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0005_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo/', verbose_name='Imagen'),
        ),
    ]
