# Generated by Django 5.2 on 2025-09-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0005_mascota'),
    ]

    operations = [
    ]
