# Generated by Django 5.2.6 on 2025-09-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_update_persona_tipo'),
        ('residencial', '0006_auto_20250927_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Visita')),
                ('fecha_hora_entrada', models.DateTimeField(verbose_name='Fecha y Hora de Entrada')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('recibe_persona', models.ForeignKey(limit_choices_to=models.Q(('tipo', 'P'), ('tipo', 'I'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='visitas_recibidas', to='administracion.persona', verbose_name='Persona que Recibe')),
                ('visitante', models.ForeignKey(limit_choices_to={'tipo': 'V'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to='administracion.persona', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visita',
                'ordering': ['-fecha_hora_entrada'],
            },
        ),
    ]
