# Generated by Django 5.2.6 on 2025-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencial', '0007_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen'),
        ),
    ]
