# Generated by Django 5.2.6 on 2025-09-21 04:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario Base')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/fotos/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('tipo', models.CharField(choices=[('E', 'Empleado'), ('R', 'Residente'), ('V', 'Visitante'), ('A', 'Administrador')], max_length=1, verbose_name='Tipo de Persona')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('CI', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de Nómina')),
                ('periodo_inicio', models.DateField(verbose_name='Período Inicio')),
                ('periodo_fin', models.DateField(verbose_name='Período Fin')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('PAG', 'Pagada'), ('C', 'Cancelada')], default='P', max_length=3, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('cantidad_horas', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cantidad de Horas')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nomina',
                'ordering': ['-fecha', 'empleado__persona__apellido'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.persona', verbose_name='Persona')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sueldo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('estado_empleado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('V', 'Vacaciones'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado del Empleado')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de Empleado')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cargo', verbose_name='Cargo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.empleado', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['persona__apellido', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('S', 'Salario'), ('B', 'Beneficio'), ('D', 'Descuento'), ('H', 'Horas Extras'), ('BON', 'Bonificación'), ('COM', 'Comisión')], max_length=3, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo Base')),
                ('beneficios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Beneficios')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuentos')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administracion.nomina', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'db_table': 'detalle_nomina',
                'ordering': ['nomina', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together={('empleado', 'periodo_inicio', 'periodo_fin')},
        ),
    ]
