# Generated by Django 5.2.6 on 2025-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('E', 'Empleado'), ('P', 'Propietario'), ('C', 'Copropietario'), ('F', 'Familiar'), ('V', 'Visitante'), ('A', 'Administrador')], max_length=1, verbose_name='Tipo de Persona'),
        ),
    ]
