# Generated by Django 5.2.6 on 2025-09-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_persona_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='DetalleNomina',
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
    ]
