# Generated by Django 5.2.6 on 2025-09-26 21:40

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_empleado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='embedding',
            field=ArrayField(models.FloatField(), blank=True, null=True, size=128, verbose_name='Embedding'),
        ),
    ]
