# Generated by Django 5.2.6 on 2025-09-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_nomina_unique_together_remove_nomina_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='supervisor',
        ),
    ]
