# Generated by Django 5.2.6 on 2025-09-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20250926_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='embedding',
        ),
    ]
