# Generated by Django 5.2 on 2025-09-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_persona_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default='1990-01-01', verbose_name='Fecha de Nacimiento'),
        ),
    ]
