# Generated by Django 5.2 on 2025-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='face_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Face Token'),
        ),
    ]
