# Generated by Django 5.2 on 2025-09-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_persona_face_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='face_token',
        ),
    ]
