# Generated by Django 5.2 on 2025-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_remove_persona_face_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario Base'),
        ),
    ]
