# Generated by Django 5.2 on 2025-09-27 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_cargo_salario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
