# Generated by Django 5.2 on 2025-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_empleado_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('P', 'Propietario'), ('I', 'Inquilino'), ('F', 'Familiar'), ('V', 'Visitante')], max_length=1, verbose_name='Tipo de Persona'),
        ),
    ]
